

/* Create Tables */

CREATE TABLE SHARE_CONTENTS
(
	SHARE_CONTENT_ID BIGINT NOT NULL COMMENT '共有コンテンツID',
	TWEET_ID BIGINT NOT NULL COMMENT 'ツイートID',
	URL VARCHAR(1000) NOT NULL COMMENT 'コンテンツURL',
	TITLE VARCHAR(1000) COMMENT 'コンテンツタイトル',
	PRIMARY KEY (SHARE_CONTENT_ID)
) COMMENT = '共有コンテンツ';


CREATE TABLE TWEETS
(
	TWEET_ID BIGINT NOT NULL COMMENT 'ツイートID',
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	TEXT VARCHAR(140) NOT NULL COMMENT 'ツイート本文',
	STATUS CHAR(3) NOT NULL COMMENT 'ツイートステータス',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日時',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時',
	PRIMARY KEY (TWEET_ID)
) COMMENT = 'ツイート';


CREATE TABLE TWEET_FAVORITES
(
	TWEET_FAVORITES_ID BIGINT NOT NULL COMMENT 'いいねID',
	TWEET_ID BIGINT NOT NULL COMMENT 'ツイートID',
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時',
	PRIMARY KEY (TWEET_FAVORITES_ID)
) COMMENT = 'NEW_TABLE';


CREATE TABLE TWEET_REPLIES
(
	TWEET_REPLY_ID BIGINT NOT NULL COMMENT 'ツイート - リプライID',
	TWEET_FROM_ID BIGINT NOT NULL COMMENT 'ツイートID(リプライ元)',
	TWEET_TO_ID BIGINT NOT NULL COMMENT 'ツイートID(リプライ先)',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時',
	PRIMARY KEY (TWEET_REPLY_ID)
) COMMENT = 'NEW_TABLE';


CREATE TABLE TWEET_RETWEETS
(
	TWEET_RETWEET_ID BIGINT NOT NULL COMMENT 'ツイート - リツイートID',
	TWEET_ID BIGINT NOT NULL COMMENT 'ツイートID',
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時',
	PRIMARY KEY (TWEET_RETWEET_ID)
) COMMENT = 'NEW_TABLE';


CREATE TABLE USERS
(
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	EMAIL VARCHAR(300) NOT NULL COMMENT 'メールアドレス',
	PASSWORD VARCHAR(300) NOT NULL COMMENT 'パスワード',
	STATUS CHAR(3) NOT NULL COMMENT 'ユーザステータス',
	VERSION BIGINT NOT NULL COMMENT 'バージョンNo',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日時',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時',
	PRIMARY KEY (USER_ID)
) COMMENT = 'ユーザ';


CREATE TABLE USER_TOKENS
(
	TOKEN VARCHAR(300) NOT NULL COMMENT 'トークン',
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	EXPIRED_AT DATETIME NOT NULL COMMENT '有効期限',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時'
) COMMENT = 'NEW_TABLE';


CREATE TABLE USER_WITHDRAWALS
(
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	REASON LONGTEXT COMMENT '退会理由',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時'
) COMMENT = 'ユーザ退会情報';



/* Create Foreign Keys */

ALTER TABLE SHARE_CONTENTS
	ADD CONSTRAINT FK_SHARE_CONTENTS_TWEETS FOREIGN KEY (TWEET_ID)
	REFERENCES TWEETS (TWEET_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_FAVORITES
	ADD CONSTRAINT FK_TWEET_FAVORITES_TWEETS FOREIGN KEY (TWEET_ID)
	REFERENCES TWEETS (TWEET_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_REPLIES
	ADD CONSTRAINT FK_TWEET_FROM_REPLIES_TWEETS FOREIGN KEY (TWEET_FROM_ID)
	REFERENCES TWEETS (TWEET_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_REPLIES
	ADD CONSTRAINT FK_TWEET_TO_REPLIES_TWEETS FOREIGN KEY (TWEET_TO_ID)
	REFERENCES TWEETS (TWEET_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_RETWEETS
	ADD CONSTRAINT FK_TWEET_RETWEETS_TWEETS FOREIGN KEY (TWEET_ID)
	REFERENCES TWEETS (TWEET_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEETS
	ADD CONSTRAINT FK_TWEETS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_FAVORITES
	ADD CONSTRAINT FK_TWEET_FAVORITES_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_RETWEETS
	ADD CONSTRAINT FK_TWEET_RETWEETS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_TOKENS
	ADD CONSTRAINT FK_USER_TOKENS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_WITHDRAWALS
	ADD CONSTRAINT FK_USER_WITHDRAWALS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



