

/* Create Tables */

CREATE TABLE COMMENTS
(
	COMMENT_ID BIGINT NOT NULL COMMENT 'コメントID',
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	URL VARCHAR(500) NOT NULL COMMENT 'シェアコンテンツURL',
	TEXT VARCHAR(140) NOT NULL COMMENT 'コメント本文',
	STATUS CHAR(3) NOT NULL COMMENT 'コメントステータス',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日時',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時',
	PRIMARY KEY (COMMENT_ID)
) COMMENT = 'ツイート';


CREATE TABLE COMMENT_FAVORITES
(
	COMMENT_FAVORITES_ID BIGINT NOT NULL COMMENT 'いいねID',
	COMMENT_ID BIGINT NOT NULL COMMENT 'コメントID',
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時',
	PRIMARY KEY (COMMENT_FAVORITES_ID)
) COMMENT = 'NEW_TABLE';


CREATE TABLE USERS
(
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	EMAIL VARCHAR(300) NOT NULL COMMENT 'メールアドレス',
	PASSWORD VARCHAR(300) NOT NULL COMMENT 'パスワード',
	STATUS CHAR(3) NOT NULL COMMENT 'ユーザステータス',
	VERSION BIGINT NOT NULL COMMENT 'バージョンNo',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日時',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時',
	PRIMARY KEY (USER_ID)
) COMMENT = 'ユーザ';


CREATE TABLE USER_TOKENS
(
	TOKEN VARCHAR(300) NOT NULL COMMENT 'トークン',
	USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
	EXPIRED_AT DATETIME NOT NULL COMMENT '有効期限',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日時'
) COMMENT = 'NEW_TABLE';



/* Create Foreign Keys */

ALTER TABLE COMMENT_FAVORITES
	ADD CONSTRAINT FK_TWEET_FAVORITES_TWEETS FOREIGN KEY (COMMENT_ID)
	REFERENCES COMMENTS (COMMENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMMENTS
	ADD CONSTRAINT FK_TWEETS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMMENT_FAVORITES
	ADD CONSTRAINT FK_TWEET_FAVORITES_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_TOKENS
	ADD CONSTRAINT FK_USER_TOKENS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



